on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'test-v*' # Push events to matching v*, i.e. v1.0, v20.15.1
  workflow_dispatch:

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Zip Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        # You may pin to the exact commit or the version.
        # uses: TheDoctor0/zip-release@b57d897cb5d60cb78b51a507f63fa184cfe35554
        uses: TheDoctor0/zip-release@0.7.6
        with:
          # Filename for archive
          filename: alathraextras_${{ github.ref }}.zip
          # Base path for archive files
          path: .
          # Working directory before zipping
          directory: .
          # List of excluded files / directories
          exclusions: .github,scripts
          # List of excluded files / directories with recursive wildcards (only applies on Windows with `zip` type)
          recursive_exclusions: .github,scripts
          # Tool to use for archiving
          type: zip
          # Provide any custom parameters to the zipping command
          #custom: # optional, default is 
          # An extra command that will run before zipping
          #command: # optional, default is 
          
